<a href="https://colab.research.google.com/github/ncmoliver/BasketballHub/blob/main/nbaDashboardProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install project packages

In [10]:
# ! pip install streamlit

In [11]:
# !pip install datasets

# Load Dataset - Team vs Team Game Stats

# Copy colab backup to project & unzip contents

In [12]:
# !cp -r "/content/drive/MyDrive/Backups/nbaDash_utils.zip" /content/

In [13]:
# import zipfile
# import os

# zip_path = "/content/nbaDash_utils.zip"  # Change this to your uploaded ZIP file name
# extract_to = "/content/"

# with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#     zip_ref.extractall(extract_to)

# print("Folder extracted successfully!")

In [14]:
# Add main.py to project folder
# !mv /content/drive/MyDrive/Backups/utils.zip /content/

# Project Start

In [15]:
# !rm -r /content/sample_data

In [16]:
# !mv /content/drive/MyDrive/Backups/nbaDash /content/

In [17]:
from utils.functions import load_data, format_data, convert_boolean_to_int, map_home_away
from utils.streamlit_functions import get_teams_by_conference, get_team_production

# Load Dataset
df = load_data("KDAM1/BasketballGames")
df.head()

,Unnamed: 0,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,0,240,240,37,85,0.435,13,33,0.394,15,...,22.2,42.4,203,116,LAC,112,1,2020,22.10.2019,False
1,1,240,240,42,81,0.519,11,31,0.355,17,...,25.0,35.8,300,125,LAL,102,0,2020,22.10.2019,True
2,2,265,265,43,102,0.422,19,45,0.422,17,...,22.2,35.7,158,114,TOR,130,1,2020,22.10.2019,False
3,3,265,265,42,103,0.408,14,40,0.350,32,...,25.0,37.7,146,124,NOP,122,0,2020,22.10.2019,True
4,4,265,265,46,108,0.426,13,43,0.302,22,...,53.2,42.0,147,116,BRK,126,1,2020,23.10.2019,True

# Calculate home and away production

In [18]:
from utils.calculations import calculate_home_production, calculate_away_production
from utils.evaluate_production import evaluate_production, compare_results, calculate_win_loss

# Calculate home and away production
df = calculate_home_production(df)
df = calculate_away_production(df)

# Evaluate the production column
df = evaluate_production(df)

# Compare the results
df = compare_results(df)

# Calculate the win/loss ratio
win_loss_ratio = calculate_win_loss(df)
df.head()

/content/utils/evaluate_production.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['home_result'] = df['home_result'].replace({'True': True, 'False': False})

,Unnamed: 0,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,...,fg3_opp_production,ft_opp_production,shooting_opp_production,ancillary_opp_production,total_opp_production,fg_opp_efficiency,fg3_opp_efficiency,ft_opp_efficiency,home_result,result_match
0,0,240,240,37,85,0.435,13,33,0.394,15,...,-27,10,-11,18.25,7.25,0.518519,0.354839,0.708333,False,pass
1,1,240,240,42,81,0.519,11,31,0.355,17,...,-21,9,-34,14.80,-19.20,0.435294,0.393939,0.714286,True,pass
2,2,265,265,43,102,0.422,19,45,0.422,17,...,-36,26,-48,19.80,-28.20,0.407767,0.350000,0.842105,True,fail
3,3,265,265,42,103,0.408,14,40,0.350,32,...,-21,14,-39,20.05,-18.95,0.421569,0.422222,0.850000,False,fail
4,4,265,265,46,108,0.426,13,43,0.302,22,...,-12,4,-18,18.25,0.25,0.475248,0.441176,0.576923,False,fail

In [19]:
df['team'].unique()

array(['LAL', 'LAC', 'NOP', 'TOR', 'MIN', 'BRK', 'CHI', 'CHO', 'WAS',
       'DAL', 'DET', 'IND', 'MEM', 'MIA', 'CLE', 'ORL', 'BOS', 'PHI',
       'SAC', 'PHO', 'DEN', 'POR', 'NYK', 'SAS', 'OKC', 'UTA', 'ATL',
       'GSW', 'MIL', 'HOU'], dtype=object)

In [20]:
df.columns

Index(['Unnamed: 0', 'mp', 'mp.1', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%',
       'ft',
       ...
       'fg3_opp_production', 'ft_opp_production', 'shooting_opp_production',
       'ancillary_opp_production', 'total_opp_production', 'fg_opp_efficiency',
       'fg3_opp_efficiency', 'ft_opp_efficiency', 'home_result',
       'result_match'],
      dtype='object', length=177)

In [21]:
data = df[['team', 'fg', 'fga', '3p', '3pa', 'ft', 'fta', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk',
       'tov', 'pf', 'pts', 'shooting_production', 'ancillary_production', 'total_production', 'team_opp', 'fg_opp', 'fga_opp', '3p_opp', '3pa_opp', 'ft_opp', 'fta_opp', 'orb_opp', 'drb_opp', 'trb_opp', 'ast_opp', 'stl_opp', 'blk_opp',
       'tov_opp', 'pf_opp', 'pts_opp', 'shooting_opp_production', 'ancillary_opp_production', 'total_opp_production']]

In [22]:
data.columns

Index(['team', 'fg', 'fga', '3p', '3pa', 'ft', 'fta', 'orb', 'drb', 'trb',
       'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'shooting_production',
       'ancillary_production', 'total_production', 'team_opp', 'fg_opp',
       'fga_opp', '3p_opp', '3pa_opp', 'ft_opp', 'fta_opp', 'orb_opp',
       'drb_opp', 'trb_opp', 'ast_opp', 'stl_opp', 'blk_opp', 'tov_opp',
       'pf_opp', 'pts_opp', 'shooting_opp_production',
       'ancillary_opp_production', 'total_opp_production'],
      dtype='object')

In [23]:
import pandas as pd

conference_data = {
    'Team_Abbreviation': [
        'ATL', 'BOS', 'BKN', 'CHA', 'CHI',
        'CLE', 'DET', 'IND', 'MIA', 'MIL',
        'NYK', 'ORL', 'PHI', 'TOR', 'WAS',
        'DAL', 'DEN', 'GSW', 'HOU', 'LAC',
        'LAL', 'MEM', 'MIN', 'NOP', 'OKC',
        'PHX', 'POR', 'SAC', 'SAS', 'UTA'
    ],
    'Conference': [
        'Eastern', 'Eastern', 'Eastern', 'Eastern', 'Eastern',
        'Eastern', 'Eastern', 'Eastern', 'Eastern', 'Eastern',
        'Eastern', 'Eastern', 'Eastern', 'Eastern', 'Eastern',
        'Western', 'Western', 'Western', 'Western', 'Western',
        'Western', 'Western', 'Western', 'Western', 'Western',
        'Western', 'Western', 'Western', 'Western', 'Western'
    ]
}

conference_df = pd.DataFrame(conference_data)
conference_df = conference_df.rename(columns={'Team_Abbreviation': 'team'})
conference_df.head()

  team Conference
0  ATL    Eastern
1  BOS    Eastern
2  BKN    Eastern
3  CHA    Eastern
4  CHI    Eastern

In [24]:
# Join the game stats with the NBA conference data on 'team'
combined_player_stats = pd.merge(
    df,
    conference_df,
    on='team',
    how='left'  # Use 'left' to keep all rows from game_stats_df
)

combined_player_stats.head()

,Unnamed: 0,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,...,ft_opp_production,shooting_opp_production,ancillary_opp_production,total_opp_production,fg_opp_efficiency,fg3_opp_efficiency,ft_opp_efficiency,home_result,result_match,Conference
0,0,240,240,37,85,0.435,13,33,0.394,15,...,10,-11,18.25,7.25,0.518519,0.354839,0.708333,False,pass,Western
1,1,240,240,42,81,0.519,11,31,0.355,17,...,9,-34,14.80,-19.20,0.435294,0.393939,0.714286,True,pass,Western
2,2,265,265,43,102,0.422,19,45,0.422,17,...,26,-48,19.80,-28.20,0.407767,0.350000,0.842105,True,fail,Western
3,3,265,265,42,103,0.408,14,40,0.350,32,...,14,-39,20.05,-18.95,0.421569,0.422222,0.850000,False,fail,Eastern
4,4,265,265,46,108,0.426,13,43,0.302,22,...,4,-18,18.25,0.25,0.475248,0.441176,0.576923,False,fail,Western

In [25]:
df.columns

Index(['Unnamed: 0', 'mp', 'mp.1', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%',
       'ft',
       ...
       'fg3_opp_production', 'ft_opp_production', 'shooting_opp_production',
       'ancillary_opp_production', 'total_opp_production', 'fg_opp_efficiency',
       'fg3_opp_efficiency', 'ft_opp_efficiency', 'home_result',
       'result_match'],
      dtype='object', length=177)

In [26]:
df = format_data(combined_player_stats)
df.head()

,season,date,team,mp,mp.1,fg,fga,fg%,3p,3pa,...,ancillary_production,total_production,fg_efficiency,fg3_efficiency,ft_efficiency,home_result,result_match,won,Conference,home_away
0,2020,22.10.2019,LAL,240,240,37,85,0.435,13,33,...,14.80,-19.20,0.435294,0.393939,0.714286,False,pass,False,Western,Home
1,2020,22.10.2019,LAC,240,240,42,81,0.519,11,31,...,18.25,7.25,0.518519,0.354839,0.708333,True,pass,True,Western,Home
2,2020,22.10.2019,NOP,265,265,43,102,0.422,19,45,...,20.05,-18.95,0.421569,0.422222,0.850000,True,fail,False,Western,Home
3,2020,22.10.2019,TOR,265,265,42,103,0.408,14,40,...,19.80,-28.20,0.407767,0.350000,0.842105,False,fail,True,Eastern,Home
4,2020,23.10.2019,MIN,265,265,46,108,0.426,13,43,...,20.65,-46.35,0.425926,0.302326,0.785714,False,fail,True,Western,Home

In [27]:
# df = format_data(df)
# df.head()

In [28]:
def rename_datetime_columns(df):

    column_mapping = {
        "date": "Date",
        "season": "Season Year",
        "team": "Team",
        "mp": "Minutes Played",
        "fg": "Two-Point Made",
        "fga": "Two-Point Attempted",
        "3p": " Three-Point Made",
        "3pa": " Three-Point Attempted",
        "ft": " Free Throws Made",
        "fta": " Free Throws Attempted",
        "orb": " Offensive Rebounds",
        "drb": " Defensive Rebounds",
        "ast": " Assists",
        "stl": " Steals",
        "blk": " Blocks",
        "tov": " Turnovers",
        "pf": " Personal Fouls",
        "pts": " Points",
        "shooting_production": " Shooting Production",
        "ancillary_production": " Ancillary Production",
        "total_production": " Production",
        "fg_effieciency" : "Two-Point Efficiency",
        "3p_effieciency" : "Three-Point Efficiency",
        "ft_effieciency" : "Free Throw Efficiency",
        "won": "Game Result"
    }

    # Convert date column to datetime datatype
    df['date'] = pd.to_datetime(df['date'], dayfirst=True)


    return df.rename(columns=column_mapping)

In [29]:
df = rename_datetime_columns(df)
df.head()

,Season Year,Date,Team,Minutes Played,mp.1,Two-Point Made,Two-Point Attempted,fg%,Three-Point Made,Three-Point Attempted,...,Ancillary Production,Production,fg_efficiency,fg3_efficiency,ft_efficiency,home_result,result_match,Game Result,Conference,home_away
0,2020,2019-10-22,LAL,240,240,37,85,0.435,13,33,...,14.80,-19.20,0.435294,0.393939,0.714286,False,pass,False,Western,Home
1,2020,2019-10-22,LAC,240,240,42,81,0.519,11,31,...,18.25,7.25,0.518519,0.354839,0.708333,True,pass,True,Western,Home
2,2020,2019-10-22,NOP,265,265,43,102,0.422,19,45,...,20.05,-18.95,0.421569,0.422222,0.850000,True,fail,False,Western,Home
3,2020,2019-10-22,TOR,265,265,42,103,0.408,14,40,...,19.80,-28.20,0.407767,0.350000,0.842105,False,fail,True,Eastern,Home
4,2020,2019-10-23,MIN,265,265,46,108,0.426,13,43,...,20.65,-46.35,0.425926,0.302326,0.785714,False,fail,True,Western,Home

In [30]:
def map_team_names(df, team_column):
    """
    Maps team names to standardized values before encoding.

    Parameters:
    df (pd.DataFrame): The DataFrame containing the team column.
    team_column (str): The name of the column containing team names.

    Returns:
    pd.DataFrame: A DataFrame with standardized team names.
    """
    team_mapping = {
        "LAL": "Los Angeles Lakers",
        "LAC": "Los Angeles Clippers",
        "GSW": "Golden State Warriors",
        "BOS": "Boston Celtics",
        "MIA": "Miami Heat",
        "CHI": "Chicago Bulls",
        "NYK": "New York Knicks",
        "PHI": "Philadelphia 76ers",
        "MIL": "Milwaukee Bucks",
        "HOU": "Houston Rockets",
        "SAS": "San Antonio Spurs",
        "TOR": "Toronto Raptors",
        "DAL": "Dallas Mavericks",
        "DEN": "Denver Nuggets",
        "UTA": "Utah Jazz",
        "OKC": "Oklahoma City Thunder",
        "POR": "Portland Trail Blazers",
        "PHX": "Phoenix Suns",
        "NOP": "New Orleans Pelicans",
        "MEM": "Memphis Grizzlies",
        "BKN": "Brooklyn Nets",
        "SAC": "Sacramento Kings",
        "IND": "Indiana Pacers",
        "WAS": "Washington Wizards",
        "CLE": "Cleveland Cavaliers",
        "ATL": "Atlanta Hawks",
        "CHA": "Charlotte Hornets",
        "DET": "Detroit Pistons",
        "ORL": "Orlando Magic",
        "MIN": "Minnesota Timberwolves",
        "CHO": "Charlotte Hornets",
        "BRK": "Brooklyn Nets",
        "PHO": "Phoenix Suns",
    }

    # Apply the mapping to the team column
    df[team_column] = df[team_column].map(team_mapping).fillna(df[team_column])  # Keep original if not in mapping

    return df

In [31]:
# Example Usage:
df = map_team_names(df, "Team")  # Standardize team names
df["Team"].unique()  # Check the updated team names

array(['Los Angeles Lakers', 'Los Angeles Clippers',
       'New Orleans Pelicans', 'Toronto Raptors',
       'Minnesota Timberwolves', 'Brooklyn Nets', 'Chicago Bulls',
       'Charlotte Hornets', 'Washington Wizards', 'Dallas Mavericks',
       'Detroit Pistons', 'Indiana Pacers', 'Memphis Grizzlies',
       'Miami Heat', 'Cleveland Cavaliers', 'Orlando Magic',
       'Boston Celtics', 'Philadelphia 76ers', 'Sacramento Kings',
       'Phoenix Suns', 'Denver Nuggets', 'Portland Trail Blazers',
       'New York Knicks', 'San Antonio Spurs', 'Oklahoma City Thunder',
       'Utah Jazz', 'Atlanta Hawks', 'Golden State Warriors',
       'Milwaukee Bucks', 'Houston Rockets'], dtype=object)

In [32]:
df.columns

Index(['Season Year', 'Date', 'Team', 'Minutes Played', 'mp.1',
       'Two-Point Made', 'Two-Point Attempted', 'fg%', ' Three-Point Made',
       ' Three-Point Attempted', '3p%', ' Free Throws Made',
       ' Free Throws Attempted', 'ft%', ' Offensive Rebounds',
       ' Defensive Rebounds', 'trb', ' Assists', ' Steals', ' Blocks',
       ' Turnovers', ' Personal Fouls', ' Points', 'total', 'fgmi', '3pmi',
       'ftmi', 'fg_production', 'fg3_production', 'ft_production',
       ' Shooting Production', ' Ancillary Production', ' Production',
       'fg_efficiency', 'fg3_efficiency', 'ft_efficiency', 'home_result',
       'result_match', 'Game Result', 'Conference', 'home_away'],
      dtype='object')

In [33]:
df = convert_boolean_to_int(df, "Game Result")
df = map_home_away(df, "home_away")
df.head()

,Season Year,Date,Team,Minutes Played,mp.1,Two-Point Made,Two-Point Attempted,fg%,Three-Point Made,Three-Point Attempted,...,Ancillary Production,Production,fg_efficiency,fg3_efficiency,ft_efficiency,home_result,result_match,Game Result,Conference,home_away
0,2020,2019-10-22,Los Angeles Lakers,240,240,37,85,0.435,13,33,...,14.80,-19.20,0.435294,0.393939,0.714286,False,pass,0,Western,1
1,2020,2019-10-22,Los Angeles Clippers,240,240,42,81,0.519,11,31,...,18.25,7.25,0.518519,0.354839,0.708333,True,pass,1,Western,1
2,2020,2019-10-22,New Orleans Pelicans,265,265,43,102,0.422,19,45,...,20.05,-18.95,0.421569,0.422222,0.850000,True,fail,0,Western,1
3,2020,2019-10-22,Toronto Raptors,265,265,42,103,0.408,14,40,...,19.80,-28.20,0.407767,0.350000,0.842105,False,fail,1,Eastern,1
4,2020,2019-10-23,Minnesota Timberwolves,265,265,46,108,0.426,13,43,...,20.65,-46.35,0.425926,0.302326,0.785714,False,fail,1,Western,1

In [34]:
df = df.drop(columns=['mp.1','home_result', 'result_match', 'fg%', '3p%', 'ft%'])

In [35]:
df.head()

,Season Year,Date,Team,Minutes Played,Two-Point Made,Two-Point Attempted,Three-Point Made,Three-Point Attempted,Free Throws Made,Free Throws Attempted,...,ft_production,Shooting Production,Ancillary Production,Production,fg_efficiency,fg3_efficiency,ft_efficiency,Game Result,Conference,home_away
0,2020,2019-10-22,Los Angeles Lakers,240,37,85,13,33,15,21,...,9,-34,14.80,-19.20,0.435294,0.393939,0.714286,0,Western,1
1,2020,2019-10-22,Los Angeles Clippers,240,42,81,11,31,17,24,...,10,-11,18.25,7.25,0.518519,0.354839,0.708333,1,Western,1
2,2020,2019-10-22,New Orleans Pelicans,265,43,102,19,45,17,20,...,14,-39,20.05,-18.95,0.421569,0.422222,0.850000,0,Western,1
3,2020,2019-10-22,Toronto Raptors,265,42,103,14,40,32,38,...,26,-48,19.80,-28.20,0.407767,0.350000,0.842105,1,Eastern,1
4,2020,2019-10-23,Minnesota Timberwolves,265,46,108,13,43,22,28,...,16,-67,20.65,-46.35,0.425926,0.302326,0.785714,1,Western,1

In [37]:
# df.to_csv('/content/nba_cleaned.csv', index=False)

In [5]:
!cp /content/nba_cleaned.csv /content/drive/MyDrive/Backups/nbaDash

In [7]:
!cp -r /content/utils /content/drive/MyDrive/Backups/nbaDash
!cp /content/main.py /content/drive/MyDrive/Backups/nbaDash

In [312]:
! npm install localtunnel

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴
added 22 packages in 2s
⠴
⠴3 packages are looking for funding
⠴  run `npm fund` for details
⠴

In [3]:
!wget -q -O - ipv4.icanhazip.com

34.139.22.161

In [4]:
!streamlit run main.py &>/content/logs.txt & npx localtunnel --port 8501

⠙your url is: https://new-steaks-move.loca.lt
^C

# Upload Player season stats data

In [ ]:
player_stats = pd.read_csv('/content/nba_cleaned.csv')
player_stats.head()

# Clean 'player_stats' dataframe
### Columns Affected
- All columns: (lowercase)
- year : Use base year + 1
  - `ex. 2012 - 13, uses 2012 + 1 to use the prominent season year`
- season typ : removes `%20` from between values

In [ ]:
def clean_data(df):
    # Extracting the first part before the '-' and ensuring it's numeric
    df['year'] = df['year'].str.split('-').str[0]
    df['year'] = pd.to_numeric(df['year'], errors='coerce')

    # Drop rows with NaN in 'year' or fill with a default value (e.g., current year)
    df = df.dropna(subset=['year'])
    df['year'] = df['year'].astype(int)

    # Increment the year by 1 to match player_stats
    df['year'] = df['year'] + 1

    # Clean up Season_type column
    df['Season_type'] = df['Season_type'].str.replace('%20', " ")

    # Convert all column names to lowercase
    df.columns = df.columns.str.lower()

    # Drop ast_tov and stl/tov cols
    df = df.drop(columns=['ast_tov', 'stl_tov'])

    return df

In [ ]:
player_stats = clean_data(player_stats)
player_stats.head()

In [ ]:
print(f"Player Stats Year Range: {player_stats['year'].min()} - {player_stats['year'].max()}")
print(f"New DataFrame Year Range: {new_df['season'].min()} - {new_df['season'].max()}")

In [ ]:
player_stats['year'] = pd.to_numeric(player_stats['year'], errors='coerce')

# Filter rows between start_year and end_year
filtered_player_stats = player_stats.loc[(player_stats['year'] >= 2020) & (player_stats['year'] <= 2022)]
filtered_player_stats = filtered_player_stats.reset_index(drop=True)
filtered_player_stats['year'].unique()

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Dictionary to store encoders for decoding later
encoders = {}

def encode_categorical_columns(df, columns):
    """
    Encodes specified categorical columns in a DataFrame.

    Parameters:
    - df (pd.DataFrame): DataFrame containing the categorical columns.
    - columns (list): List of column names to encode.

    Returns:
    - pd.DataFrame: DataFrame with encoded categorical columns.
    """
    global encoders  # Store encoders globally for decoding
    df_encoded = df.copy()

    for column in columns:
        if column in df_encoded.columns and len(df_encoded[column]) > 2:
            le = LabelEncoder()
            df_encoded[column] = le.fit_transform(df_encoded[column])
            encoders[column] = le  # Save the encoder for later decoding
        else:
            unique_values = df_encoded[column].unique()
            if len(unique_values) == 2:
              mapping = {unique_values[0]: 0, unique_values[1]: 1}
              encoders[column] = mapping
              df_encoded[column] = df_encoded[column].map(mapping)

    return df_encoded

def decode_categorical_columns(df, columns):
    """
    Decodes previously encoded categorical columns in a DataFrame.

    Parameters:
    - df (pd.DataFrame): DataFrame with encoded categorical columns.
    - columns (list): List of column names to decode.

    Returns:
    - pd.DataFrame: DataFrame with decoded categorical columns.
    """
    df_decoded = df.copy()

    for column in columns:
        if column in encoders and column in df_decoded.columns:
            le = encoders[column]
            df_decoded[column] = le.inverse_transform(df_decoded[column])

    return df_decoded

In [ ]:
display(new_df.head())
display(filtered_player_stats.head())

# Add player production columns to `filtered_df`

In [ ]:
filtered_player_stats = calculate_player_production(filtered_player_stats)
filtered_player_stats.head()

In [ ]:
filtered_player_stats.columns

In [ ]:
# Join the game stats with the NBA conference data on 'team'
combined_team_stats = pd.merge(
    new_df,
    conference_df,
    on='team',
    how='left'  # Use 'left' to keep all rows from game_stats_df
)

combined_team_stats.head()

In [ ]:
display(combined_player_stats.head())
display(combined_team_stats.head())

In [ ]:
# from google.colab import files
# import zipfile
# import os

# # Upload the zip file
# uploaded = files.upload()

# # Get the file name
# filename = list(uploaded.keys())[0]

# # Unzip the file
# with zipfile.ZipFile(filename, 'r') as zip_ref:
#     zip_ref.extractall('/content/nba_logos')  # Change 'folder_name' to your desired directory

# # Verify contents
# print("Files in extracted folder:", os.listdir('/content/nba_logos'))

# Create dataframe for nba logos
### Create a dataframe of nba abbreviations and map them to each image in the dataset

In [ ]:
import pandas as pd
from PIL import Image
import numpy as np
import os

In [ ]:
# Change directory to the folder containing the images
image_folder = '/content/nba_logos/nba_logos'
os.chdir(image_folder)

# Get all image file names
image_files = [f for f in os.listdir() if f.endswith(('png', 'jpg', 'jpeg', 'gif'))]

# Create an empty list to hold image data
image_data = []

# Loop through each image file
for image_file in image_files:
    # Open image using PIL
    image = Image.open(image_file)

    # Get image properties
    file_name = image_file
    file_path = os.path.join(image_folder, image_file)
    width, height = image.size
    mode = image.mode

    # Optional: Convert image to numpy array
    image_array = np.array(image)

    # Append data to the list
    image_data.append({
        'File Name': file_name,
        'File Path': file_path,
        'Width': width,
        'Height': height,
        'Mode': mode,
        'Image Array': image_array
    })

# Create a DataFrame from the list
df_images = pd.DataFrame(image_data)

# Display the DataFrame
df_images.head()

## Resize each image to 640 x 640

In [ ]:
5 # Create an empty list to hold image data
image_data = []

# Loop through each image file
for image_file in image_files:
    # Open image using PIL
    image = Image.open(image_file)

    # Get image properties
    file_name = image_file
    file_path = os.path.join(image_folder, image_file)
    width, height = image.size
    mode = image.mode

    # Optional: Convert image to numpy array
    image_array = np.array(image)

    # Append data to the list
    image_data.append({
        'File Name': file_name,
        'File Path': file_path,
        'Width': width,
        'Height': height,
        'Mode': mode,
        'Image Array': image_array
    })

# Create a DataFrame from the list
df_images = pd.DataFrame(image_data)
df_images['Width'] = 640
df_images['Height'] = 640
df_images.head()

In [ ]:
df_images.columns

In [ ]:
df_images = df_images[['File Name', 'File Path']]
df_images.head()

In [ ]:
# Extract first three letters and map to team names
df_images['team'] = df_images['File Name'].str[:3].str.upper()

In [ ]:
df_images.head()

# Remove google_colab `\content\` folder

In [ ]:
# for file in df_images['File Path']:
#   file = df_images['File Path'].str.replace('/content', ' ')
#   df_images['File Path'] = file
# df_images.head()

In [ ]:
# from google.colab import sheets
# sheet = sheets.InteractiveSheet(df=df_images)

# Upload dataset to kaggle

In [ ]:
# import json
# home_folder = '/content'
# os.chdir(home_folder)
# # Convert to JSON
# json_output = df_images.to_json(orient='records')

In [ ]:
# import json

# # Pretty print the JSON
# parsed_json = json.loads(json_output)

# # Save as a JSON file
# with open('kaggle.json', 'w') as f:
#     json.dump(parsed_json, f, indent=4)

In [ ]:
# !mkdir -p ~/.kaggle
# !mv /content/kaggle.json ~/.kaggle/
# !chmod 600 ~/.kaggle/kaggle.json

# Uploading Notes
- kaggle.json is downloaded from kaggle, not other changes necessary.
- dataset-metadata.json must be in same project folder
  * `Ex:/content/nba_logos`

In [ ]:
# !kaggle datasets create -p /content/nba_logos --dir-mode zip

# Add logos to current data

In [ ]:
display(combined_player_stats.head())
display(df_images.head())

In [ ]:
# Merge the DataFrames on the Team Name
df_merged_player = pd.merge(
    combined_player_stats,
    df_images,
    on='team',
    how='inner'  # Use 'inner' to only keep matching rows
)

# Display the merged DataFrame
df_merged_player = df_merged_player.rename(columns={'File Name': 'logo_name', 'File Path': 'logo_path'})
df_merged_player.head()

In [ ]:
# Merge the DataFrames on the Team Name
df_merged_team = pd.merge(
    combined_team_stats,
    df_images,
    on='team',
    how='inner'  # Use 'inner' to only keep matching rows
)

# Display the merged DataFrame
df_merged_team = df_merged_team.rename(columns={'File Name': 'logo_name', 'File Path': 'logo_path'})
df_merged_team.head()

# Convert to csv and upload to google colab, data folder

In [ ]:
display(df_merged_player.head())
display(df_merged_team.head())

In [ ]:
df_merged_player.to_csv('/content/cleaned_player_stats.csv', index=False)
df_merged_team.to_csv('/content/cleaned_team_stats.csv', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#Save the DataFrame as a CSV file in Google Drive
df_merged_player.to_csv('/content/drive/MyDrive/Data/cleaned_nba_player_stats.csv', index=False)
df_merged_team.to_csv('/content/drive/MyDrive/Data/cleaned_nba_teamVteam_stats.csv', index=False)

#